version: "3.8"

volumes:
  hadoop_datanode1:
  hadoop_namenode:
  hadoop_historyserver:


networks:
  spark-net:
    driver: bridge

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    networks: [ spark-net ]
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data:/home/nbs/data
    environment:
      - CLUSTER_NAME=test
    env_file: [ ./hadoop.env ]

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    depends_on: [ namenode ]
    networks: [ spark-net ]
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file: [ ./hadoop.env ]

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    depends_on: [ namenode, datanode1 ]
    networks: [ spark-net ]
    ports:
      - "8089:8088"
    env_file: [ ./hadoop.env ]

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    depends_on: [ namenode, datanode1 ]
    networks: [ spark-net ]
    env_file: [ ./hadoop.env ]

  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    depends_on: [ namenode ]
    networks: [ spark-net ]
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - NAMENODE_HOSTNAME=namenode

  spark-worker-1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    depends_on: [ spark-master, namenode ]
    networks: [ spark-net ]
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - NAMENODE_HOSTNAME=namenode

  jupyternb:
    image: jupyter/all-spark-notebook:42f4c82a07ff
    container_name: jupyternb
    user: root
    depends_on: [ spark-master ]
    networks: [ spark-net ]
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work/data
      - ./events:/tmp/spark-events
    command: >
      start-notebook.sh --ip=0.0.0.0 --allow-root --NotebookApp.token=''
